name: Run Cypress Tests

on:
  push:
    branches:
      - cypress-homework-branch8
  pull_request:
    branches:
      - cypress-homework-branch8

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.13.1
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests in Docker
      run: docker run -it -v ${PWD}:/e2e -w /e2e cypress/included:13.13.1

    - name: Upload Cypress videos
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos
        path: cypress/videos

    - name: Upload Cypress screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress/screenshots
